#Service Configuration
spring:
  application:
    name: gateway-service

info:
  component: Edge Server

#Server Configuration
server:
  port: 10000

#Zuul Configuration
zuul:
  routes:
    batches:
      path: /batches/**
      stripPrefix: true
      serviceId: batch-service
    trainees:
      path: /trainees/**
      stripPrefix: true
      serviceId: user-service
    trainers:
      path: /trainers/**
      stripPrefix: true
      serviceId: user-service
    users:
      path: /users/**
      stripPrefix: true
      serviceId: user-service
    skills:
      path: /skills/**
      stripPrefix: true
      serviceId: skills-service

endpoints:
  beans:
    enabled: true
    sensitive: false
  loggers:
    enabled: true
    sensitive: false
  jolokia:
    enabled: true
    sensitive: false

#Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOME}
